config/routes.rb
Rails.application.routes.draw do
 
    devise_for :users
    resources :items do
        member do
            patch :complete
        end
    end
    root 'items#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
    belongs_to :user
    
    def complete?
        !completed_at.blank?
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :find_item, only: [:show, :edit, :update, :destroy]
    
    def index
        if user_signed_in?
            @items = Item.where(:user_id => current_user.id).order("created_at DESC")
        end
    end
    
    def show
       
    end
    
    def new
        @item = current_user.items.build
    end
    
    def create
        @item = current_user.items.build(item_params)
        
        if @item.save
            redirect_to root_path
        else
            render 'new'
        end
    end
    
    def edit
        
    end
    
    def update
        if @item.update(item_params)
            redirect_to item_path(@item)
        else
            render 'edit'
        end
    end
    
    def destroy
        @item.destroy
        redirect_to root_path
    end
    
    def complete
        @item = Item.find(params[:id])
        @item.update_attribute(:completed_at, Time.now)
        redirect_to root_path
    end
    
    private
    def item_params
        params.require(:item).permit(:title, :description)
    end
    
    def find_item
        @item = Item.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/common/_top.html.erb
 
<nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "ToDolist", root_path, class:"navbar-brand"%>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.present? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path%></li>
          <li><%= link_to "Sign up", new_user_registration_path%></li>
        <% end %>
        
      </ul>
      <% if user_signed_in? %>
        <%= link_to "Create Item", new_item_path, class: "navbar-text navbar-link" %>
      <% end %>
    </div>  
    
    
</nav>

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
    <%= f.input :title, label: "Item Title"  %>
    <%= f.input :description  %>
    <%= f.button :submit  %>
<% end %>

app/views/items/_welcome_page.html.erb
<div class="jumbotron">
    <h2>ToDolist! You Need TO DO!  </h2>
    <br>
    <h3>Trusted by Millions. It's Really waste Your time!!</h3>
    <br>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-danger"%>
    
</div>

app/views/items/edit.html.erb
    <div class="col-md-8 col-md-offset-2">
        <h1>Edit Todo Item</h1>
        
        <%= render 'form' %>
        
    </div>

app/views/items/index.html.erb
<% if user_signed_in? %>
  <div class="col-md-10 col-md-offset-1">
    <% @items.each do |item| %>
      <div class="index-wrapper">
          
        <% if item.complete? %>
          <div class="row item">
            <div class="col-md-2">
              <p><%= link_to complete_item_path(item), method: :patch do %></p>
                    <i class="fa fa-check fa-lg"></i>
                 <% end %>
            </div>
            <div class="col-md-2">
              <p><%= link_to item, method: :delete, data: {confirm: "Are you sure?"} do %></p>
                    <i class="fa fa-trash fa-lg"></i>
                <% end %>
            </div>
            <div class="col-md-8">
              <h2 style="opacity: 0.5;" class="item-title"><strike><%= link_to item.title, item %></strike></h2>
              <p style="opacity: 0.5;" class="item-sub-title item-desc"><%= item.description %></p>
              <p style="opacity: 0.5;" class="time-created-at item-sub-title">Completed <%= time_ago_in_words(item.completed_at) %> ago</p>
            </div>
          </div>
        <% else %>
          <div class="row item">
            <div class="col-md-2">
              <p><%= link_to complete_item_path(item), method: :patch do %></p>
                    <i class="fa fa-check fa-lg"></i>
                 <% end %>
            </div>
            <div class="col-md-8">
              <h2 class="item-title"><%= link_to item.title, item %></h2>
              <p class="item-sub-title item-desc"><%= item.description %></p>
              <p style="opacity: 0.5;" class="time-created-at item-sub-title">Created <%= time_ago_in_words(item.created_at) %> ago</p>
            </div>
            <div class="col-md-2">
              <p><%= link_to item, method: :delete, data: {confirm: "Are you sure?"} do %></p>
                    <i class="fa fa-trash fa-lg"></i>
                <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% else %>
  <%= render 'welcome_page' %>
<% end %>

app/views/items/new.html.erb
    <div class="col-md-8 col-md-offset-2">
        <h1>New Todo Item</h1>
        
        <%= render 'form' %>
        
    </div>

app/views/items/show.html.erb
<div class="col-md-10 col-md-offset-1">
    <h2><%= @item.title %></h2>
    <p><%= @item.description %></p>
    
    <div class="col-md-4 col-md-offset-4">
        <%= link_to "Back", root_path %>
        <%= link_to "Edit", edit_item_path %>
        <%= link_to "Delete", item_path(@item), method: :delete, data: { confirm: "Are You sure ?" }  %>
        
    </div>
    
</div>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

</head>
<body>
    <%= render "common/top" %>
  
 
  <div class="container">
   
    <%= yield %>
  </div>

</body>
</html>